# Generated by Django 3.2.4 on 2021-10-07 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_workflow_engine', '0002_alter_flow_workflow_name'),
        ('leavers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AddField(
            model_name='leavingrequest',
            name='flow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaving_request', to='django_workflow_engine.flow'),
            preserve_default=False,
        ),
    ]
