# Generated by Django 3.2.8 on 2021-11-22 13:17

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leavers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="govuk_paas_access_removed",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="govuk_paas_access_task_log",
                to="leavers.tasklog",
            ),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="slack_removed",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slack_access_task_log",
                to="leavers.tasklog",
            ),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_logs",
                to="user.user",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="SlackMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("slack_timestamp", models.CharField(max_length=100)),
                ("channel_id", models.CharField(max_length=100)),
                (
                    "leaving_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slack_messages",
                        to="leavers.leavingrequest",
                    ),
                ),
            ],
        ),
    ]
