# Generated by Django 3.2.8 on 2021-10-13 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leavers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="leaver_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaving_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="requesting_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requesting_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
