# Generated by Django 3.2.4 on 2021-10-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavers', '0002_auto_20211007_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavingrequest',
            name='for_self',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leavingrequest',
            name='last_day',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
