# Generated by Django 3.2.4 on 2021-10-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leavers', '0003_auto_20211007_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavingrequest',
            name='hardware_received',
            field=models.BooleanField(default=False),
        ),
    ]
