# Generated by Django 3.2.8 on 2021-11-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0003_auto_20211122_1511"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaverInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("leaver_email", models.EmailField(max_length=254, unique=True)),
                ("updates", models.JSONField()),
                ("leaving_date", models.DateTimeField(blank=True, null=True)),
                ("information_is_correct", models.BooleanField(null=True)),
                ("additional_information", models.CharField(max_length=1000)),
                (
                    "return_option",
                    models.CharField(
                        choices=[
                            ("office", "Return at the office"),
                            ("home", "Collection from home"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "return_personal_phone",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                (
                    "return_contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "return_address",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
            ],
        ),
    ]
