# Generated by Django 3.2.8 on 2021-11-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0003_auto_20211122_1511"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaverUpdates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("leaver_email", models.EmailField(max_length=254, unique=True)),
                ("updates", models.JSONField()),
            ],
        ),
    ]
