# Generated by Django 3.2.9 on 2021-12-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0004_leaverinformation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverinformation",
            name="return_address",
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="return_address_building_and_street",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="return_address_city",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="return_address_county",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="return_address_postcode",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
