# Generated by Django 3.2.9 on 2021-12-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0005_reformat_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="building_pass_access_revoked",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="building_pass_access_task_log",
                to="leavers.tasklog",
            ),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="rosa_access_revoked",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rosa_access_task_log",
                to="leavers.tasklog",
            ),
        ),
    ]
