# Generated by Django 3.2.9 on 2021-12-30 15:47

import django.db.models.deletion
from django.db import migrations, models


def delete_all_leaving_requests(apps, schema_editor):
    """
    This migration is so that deployments to Dev will succeed.

    Note: We should squash migrations and remove this method when we are ready
    to deploy to Prod. /PS-IGNORE
    """
    LeavingRequest = apps.get_model("leavers", "LeavingRequest")
    LeavingRequest.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0001_initial"),
        ("leavers", "0006_auto_20211221_1656"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverinformation",
            name="leaving_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaver_information",
                to="leavers.leavingrequest",
            ),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="leaver_activitystream_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="activity_stream.activitystreamstaffssouser",
            ),
        ),
        migrations.RunPython(delete_all_leaving_requests, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="leaverinformation",
            name="leaving_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaver_information",
                to="leavers.leavingrequest",
            ),
        ),
        migrations.AlterField(
            model_name="leavingrequest",
            name="leaver_activitystream_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="activity_stream.activitystreamstaffssouser",
            ),
        ),
    ]
