# Generated by Django 3.2.9 on 2022-01-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0007_leaverinformation_add_asuser_and_leavingrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavingrequest",
            name="leaver_sso_id",
        ),
    ]
