# Generated by Django 3.2.9 on 2022-01-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0002_activitystreamstaffssouser_available"),
        ("leavers", "0008_remove_leavingrequest_leaver_sso_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="manager_activitystream_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="activity_stream.activitystreamstaffssouser",
            ),
        ),
        migrations.AlterField(
            model_name="leavingrequest",
            name="leaver_activitystream_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="activity_stream.activitystreamstaffssouser",
            ),
        ),
    ]
