# Generated by Django 3.2.9 on 2022-01-19 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0002_activitystreamstaffssouser_available"),
        ("leavers", "0009_auto_20220107_1909"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="data_recipient_activitystream_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="activity_stream.activitystreamstaffssouser",
            ),
        ),
    ]
