# Generated by Django 3.2.9 on 2022-01-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0012_auto_20220121_1300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavingrequest",
            name="security_clearance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ctc", "Counter Terrorist Check"),
                    ("sc", "Security Check"),
                    ("esc", "Enhanced Security Check"),
                    ("dv", "Developed Vetting"),
                    ("edv", "Enhanced Developed Vetting"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
