# Generated by Django 3.2.11 on 2022-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0013_alter_leavingrequest_security_clearance"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverinformation",
            name="directorate_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="job_title",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="leaver_first_name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="leaver_last_name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="personal_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="staff_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="leaverinformation",
            name="return_option",
            field=models.CharField(
                choices=[
                    ("office", "Return at the office"),
                    ("home", "Collection from home"),
                ],
                max_length=10,
            ),
        ),
    ]
