# Generated by Django 3.2.11 on 2022-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0014_auto_20220128_1557"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverinformation",
            name="has_dse",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="locker_number",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="leaverinformation",
            name="return_option",
            field=models.CharField(
                choices=[
                    ("office", "Return at the office"),
                    ("home", "Collection from home"),
                ],
                max_length=10,
            ),
        ),
    ]
