# Generated by Django 3.2.11 on 2022-01-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0015_auto_20220128_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverinformation",
            name="cirrus_assets",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="dse_assets",
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="leaverinformation",
            name="return_option",
            field=models.CharField(
                choices=[
                    ("office", "Return at the office"),
                    ("home", "Collection from home"),
                ],
                max_length=10,
            ),
        ),
    ]
