# Generated by Django 3.2.11 on 2022-01-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0016_auto_20220131_1538"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverinformation",
            name="cirrus_assets",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaverinformation",
            name="dse_assets",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaverinformation",
            name="return_option",
            field=models.CharField(
                choices=[
                    ("office", "Return at the office"),
                    ("home", "Collection from home"),
                ],
                max_length=10,
            ),
        ),
    ]
