# Generated by Django 3.2.11 on 2022-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0017_auto_20220131_1659"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="sre_complete",
            field=models.BooleanField(default=False),
        ),
    ]
