# Generated by Django 3.2.11 on 2022-02-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0018_auto_20220207_1314"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="task_logs",
            field=models.ManyToManyField(to="leavers.TaskLog"),
        ),
        migrations.AlterField(
            model_name="leaverinformation",
            name="return_option",
            field=models.CharField(
                choices=[
                    ("office", "Return at the office"),
                    ("home", "Collection from home"),
                ],
                max_length=10,
            ),
        ),
    ]
