# Generated by Django 3.2.11 on 2022-02-23 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0020_leavingrequest_line_manager_complete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavingrequest",
            name="line_manager_complete",
        ),
        migrations.RemoveField(
            model_name="leavingrequest",
            name="sre_complete",
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="line_manager_complete",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="sre_complete",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
