# Generated by Django 3.2.12 on 2022-03-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0021_auto_20220223_1539"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="security_team_complete",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
