# Generated by Django 3.2.12 on 2022-03-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0022_leavingrequest_security_team_complete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavingrequest",
            name="leaver_first_name",
        ),
        migrations.RemoveField(
            model_name="leavingrequest",
            name="leaver_last_name",
        ),
    ]
