# Generated by Django 3.2.12 on 2022-03-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0023_auto_20220311_1553"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavingrequest",
            name="hardware_received",
        ),
    ]
