# Generated by Django 3.2.12 on 2022-03-11 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0024_remove_leavingrequest_hardware_received"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavingrequest",
            name="building_pass_access_revoked",
        ),
        migrations.RemoveField(
            model_name="leavingrequest",
            name="rosa_access_revoked",
        ),
    ]
