# Generated by Django 3.2.12 on 2022-03-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0025_auto_20220311_1629"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="rosa_key_returned",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rosa_key_returned_task_log",
                to="leavers.tasklog",
            ),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="rosa_laptop_returned",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rosa_laptop_returned_task_log",
                to="leavers.tasklog",
            ),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="security_pass",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_pass_task_log",
                to="leavers.tasklog",
            ),
        ),
    ]
