# Generated by Django 3.2.12 on 2022-03-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0026_auto_20220311_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="email_task_logs",
            field=models.ManyToManyField(
                related_name="_leavers_leavingrequest_email_task_logs_+",
                to="leavers.TaskLog",
            ),
        ),
    ]
