# Generated by Django 3.2.12 on 2022-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0027_leavingrequest_email_task_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="leaving_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
