# Generated by Django 3.2.12 on 2022-03-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0028_leavingrequest_leaving_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverinformation",
            name="last_day",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
