# Generated by Django 3.2.12 on 2022-03-31 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0029_leaverinformation_last_day"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="leaver_complete",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
