# Generated by Django 3.2.12 on 2022-04-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0030_leavingrequest_leaver_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverinformation",
            name="return_option",
            field=models.CharField(
                choices=[
                    ("office", "Return to the office"),
                    ("home", "Home collection"),
                ],
                max_length=10,
            ),
        ),
    ]
