# Generated by Django 3.2.13 on 2022-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0031_alter_leaverinformation_return_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="reason_for_leaving",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resignation", "Resignation"),
                    ("end_of_contract", "End of contract"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
