# Generated by Django 3.2.13 on 2022-05-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0032_leavingrequest_reason_for_leaving"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="annual_leave",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deducted", "Deducted"),
                    ("paid", "Paid"),
                    (None, "No annual leave"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="annual_leave_measurement",
            field=models.CharField(
                blank=True,
                choices=[("days", "Days"), ("hours", "Hours")],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="annual_number",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="flexi_leave",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deducted", "Deducted"),
                    ("paid", "Paid"),
                    (None, "No flexi leave"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="flexi_number",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
