# Generated by Django 3.2.13 on 2022-05-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0033_auto_20220509_1427"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="staff_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("civil_servant", "Civil servant"),
                    ("fast_streamers", "Fast streamers"),
                    ("contractor", "Contractor such as Green Park"),
                    ("bench_contractor", "Bench contractor such as Profusion"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
