# Generated by Django 3.2.13 on 2022-05-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0034_leavingrequest_staff_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavingrequest",
            name="annual_leave",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deducted", "Deducted"),
                    ("paid", "Paid"),
                    ("None", "No annual leave"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="leavingrequest",
            name="flexi_leave",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deducted", "Deducted"),
                    ("paid", "Paid"),
                    ("None", "No flexi leave"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
