# Generated by Django 3.2.13 on 2022-06-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0035_auto_20220519_1121"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverinformation",
            name="locker_number",
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="has_locker",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
