# Generated by Django 3.2.13 on 2022-06-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0035_auto_20220519_1121"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavingrequest",
            name="security_team_complete",
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="security_team_building_pass_complete",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="security_team_rosa_kit_complete",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
