# Generated by Django 3.2.13 on 2022-06-09 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0036_auto_20220608_1402"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavingrequest",
            name="security_team_complete",
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="security_team_building_pass_complete",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="security_team_rosa_kit_complete",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name="leavingrequest",
            old_name="security_pass",
            new_name="security_pass_destroyed",
        ),
        migrations.AlterField(
            model_name="leavingrequest",
            name="security_pass_destroyed",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_pass_destroyed_task_log",
                to="leavers.tasklog",
            ),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="security_pass_not_returned",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_pass_not_returned_task_log",
                to="leavers.tasklog",
            ),
        ),
    ]
