# Generated by Django 3.2.13 on 2022-06-09 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0036_auto_20220609_1544"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leavingrequest",
            old_name="security_pass",
            new_name="security_pass_destroyed",
        ),
    ]
