# Generated by Django 3.2.13 on 2022-06-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0037_auto_20220609_1544"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="notes",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
