# Generated by Django 3.2.13 on 2022-06-09 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0037_rename_security_pass_leavingrequest_security_pass_destroyed"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="security_pass_not_returned",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_pass_not_returned_task_log",
                to="leavers.tasklog",
            ),
        ),
        migrations.AlterField(
            model_name="leavingrequest",
            name="security_pass_destroyed",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_pass_destroyed_task_log",
                to="leavers.tasklog",
            ),
        ),
    ]
