# Generated by Django 3.2.13 on 2022-06-10 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0038_tasklog_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="rosa_kit_form_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="rosa_mobile_returned",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rosa_mobile_returned_task_log",
                to="leavers.tasklog",
            ),
        ),
    ]
