# Generated by Django 3.2.13 on 2022-07-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0039_auto_20220610_1209"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverinformation",
            name="leaver_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
