# Generated by Django 3.2.13 on 2022-05-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0041_auto_20220527_1247"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavingrequest",
            name="uksbs_pdf_data",
        ),
    ]
