# Generated by Django 3.2.13 on 2022-05-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0042_remove_leavingrequest_uksbs_pdf_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="line_reports",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
