# Generated by Django 3.2.13 on 2022-07-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0043_leavingrequest_line_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="leaver_paid_unpaid",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unpaid", "Unpaid - not on UK SBS Payroll"),
                    ("paid", "Paid - on UK SBS Payroll"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
