# Generated by Django 3.2.14 on 2022-07-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0044_leavingrequest_leaver_paid_unpaid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverinformation",
            name="return_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("office", "Return to the office"),
                    ("home", "Home collection"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
