# Generated by Django 3.2.14 on 2022-07-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0045_alter_leaverinformation_return_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavingrequest",
            name="annual_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leavingrequest",
            name="flexi_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
