# Generated by Django 3.2.14 on 2022-07-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0048_leaverinformation_leaver_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverinformation",
            name="leaver_email",
        ),
    ]
