# Generated by Django 3.2.14 on 2022-07-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0049_remove_leaverinformation_leaver_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverinformation",
            name="contact_address_county",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.RenameField(
            model_name="leaverinformation",
            old_name="contact_address_town",
            new_name="contact_address_city",
        ),
        migrations.RenameField(
            model_name="leaverinformation",
            old_name="return_address_building_and_street",
            new_name="return_address_line_1",
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="return_address_line_2",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.RenameField(
            model_name="leaverinformation",
            old_name="contact_address_line1",
            new_name="contact_address_line_1",
        ),
        migrations.RenameField(
            model_name="leaverinformation",
            old_name="contact_address_line2",
            new_name="contact_address_line_2",
        ),
    ]
