# Generated by Django 3.2.14 on 2022-07-25 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("leavers", "0051_alter_leavingrequest_security_clearance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasklog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
