# Generated by Django 3.2.14 on 2022-07-27 14:19

from typing import TYPE_CHECKING

import django.db.models.deletion
from django.db import migrations, models

if TYPE_CHECKING:
    from django.db.models.query import QuerySet

    from leavers.models import LeavingRequest


def set_processing_manager_activitystream_user(apps, schema_editor):
    LeavingRequest: "LeavingRequest" = apps.get_model("leavers", "LeavingRequest")
    leaving_requests: QuerySet["LeavingRequest"] = LeavingRequest.objects.all()
    for leaving_request in leaving_requests:
        if leaving_request.leaver_complete:
            leaving_request.processing_manager_activitystream_user = (
                leaving_request.manager_activitystream_user
            )
        leaving_request.save()


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0010_activitystreamstaffssouser_uksbs_person_id"),
        ("leavers", "0052_alter_tasklog_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="processing_manager_activitystream_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="activity_stream.activitystreamstaffssouser",
            ),
        ),
        migrations.RunPython(set_processing_manager_activitystream_user),
    ]
