# Generated by Django 3.2.14 on 2022-07-26 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0053_leavingrequest_processing_manager_activitystream_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverinformation",
            name="directorate_id",
        ),
    ]
