# Generated by Django 3.2.15 on 2022-08-23 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0054_remove_leaverinformation_directorate_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="security_pass_disabled",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_pass_disabled_task_log",
                to="leavers.tasklog",
            ),
        ),
        migrations.AddField(
            model_name="leavingrequest",
            name="security_pass_returned",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_pass_returned_task_log",
                to="leavers.tasklog",
            ),
        ),
    ]
