# Generated by Django 3.2.15 on 2022-09-14 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0056_unpause_workflows"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="manually_offboarded_from_uksbs",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manually_offboarded_from_uksbs",
                to="leavers.tasklog",
            ),
        ),
    ]
