# Generated by Django 3.2.15 on 2022-09-15 13:05

from django.db import migrations, models

LEAVING_REQUEST_TASK_LOG_FIELDS = [
    "vpn_access_removed",
    "govuk_paas_access_removed",
    "github_user_access_removed",
    "sentry_access_removed",
    "slack_removed",
    "sso_access_removed",
    "aws_access_removed",
    "jira_access_removed",
    "security_pass_destroyed",
    "security_pass_disabled",
    "security_pass_returned",
    "security_pass_not_returned",
    "rosa_mobile_returned",
    "rosa_laptop_returned",
    "rosa_key_returned",
    "manually_offboarded_from_uksbs",
]


def update_tasklogs_with_references(apps, schema_editor):
    LeavingRequest = apps.get_model("leavers", "LeavingRequest")
    for leaving_request in LeavingRequest.objects.all():
        for field_name in LEAVING_REQUEST_TASK_LOG_FIELDS:
            task_log = getattr(leaving_request, field_name)
            if task_log:
                task_log.reference = f"LeavingRequest.{field_name}"
                task_log.save()


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0056_unpause_workflows"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="reference",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.RunPython(
            update_tasklogs_with_references, migrations.RunPython.noop
        ),
    ]
