# Generated by Django 3.2.15 on 2022-09-21 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0059_update_uksbs_task_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="gitlab_user_access_removed",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gitlab_user_task_log",
                to="leavers.tasklog",
            ),
        ),
    ]
