# Generated by Django 3.2.15 on 2022-09-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0060_leavingrequest_gitlab_user_access_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklog",
            name="value",
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
