# Generated by Django 3.2.15 on 2022-09-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0062_alter_leavingrequest_staff_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavingrequest",
            name="security_pass_not_returned",
        ),
    ]
