# Generated by Django 3.2.15 on 2022-09-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0063_remove_leavingrequest_security_pass_not_returned"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavingrequest",
            name="rosa_kit_form_data",
        ),
    ]
