# Generated by Django 3.2.15 on 2022-10-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0064_remove_leavingrequest_rosa_kit_form_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaverinformation",
            name="additional_information",
        ),
        migrations.RemoveField(
            model_name="leaverinformation",
            name="has_locker",
        ),
        migrations.RemoveField(
            model_name="leaverinformation",
            name="information_is_correct",
        ),
        migrations.AlterField(
            model_name="leaverinformation",
            name="return_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("office", "In-person return at OAB"),
                    ("home", "Home collection by courier"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
