# Generated by Django 3.2.15 on 2022-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0065_auto_20221010_1645"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavingrequest",
            name="staff_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("civil_servant", "Civil servant"),
                    ("contractor", "Contractor (for example, Hays)"),
                    ("bench_contractor", "Bench contractor (for example, Profusion)"),
                    ("fast_streamers", "Civil Service Fast Stream"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
