# Generated by Django 3.2.15 on 2022-10-13 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0066_alter_leavingrequest_staff_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavingrequest",
            name="leaver_paid_unpaid",
            field=models.CharField(
                blank=True,
                choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                max_length=255,
                null=True,
            ),
        ),
    ]
