# Generated by Django 3.2.15 on 2022-10-18 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0067_alter_leavingrequest_leaver_paid_unpaid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leavingrequest",
            name="sso_access_removed",
        ),
    ]
