# Generated by Django 4.0.8 on 2022-10-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0069_alter_leavingrequest_email_task_logs"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="service_now_offline",
            field=models.BooleanField(default=False),
        ),
    ]
