# Generated by Django 4.0.8 on 2022-10-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0070_leavingrequest_service_now_offline"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="line_manager_service_now_complete",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
