# Generated by Django 4.0.8 on 2022-11-07 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activity_stream",
            "0017_alter_activitystreamstaffssouseremail_email_address_and_more",
        ),
        ("leavers", "0071_leavingrequest_line_manager_service_now_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavingrequest",
            name="leaver_activitystream_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leaving_requests",
                to="activity_stream.activitystreamstaffssouser",
            ),
        ),
    ]
