# Generated by Django 4.0.8 on 2022-11-22 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0072_alter_leavingrequest_leaver_activitystream_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="trello_user_access_removed",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trello_user_task_log",
                to="leavers.tasklog",
            ),
        ),
    ]
