# Generated by Django 4.1.3 on 2022-12-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0073_leavingrequest_trello_user_access_removed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavingrequest",
            name="reason_for_leaving",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resignation", "Resignation"),
                    ("retirement", "Retirement"),
                    ("transfer", "Transferring to another Civil Service role"),
                    ("end_of_contract", "End of contract"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
