# Generated by Django 4.1.4 on 2023-01-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0076_update_flows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavingrequest",
            name="annual_number",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="leavingrequest",
            name="flexi_number",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=7, null=True
            ),
        ),
    ]
