# Generated by Django 4.1.4 on 2023-01-06 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0078_leavingrequest_security_clearance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="security_clearance_level",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="security_clearance_level_task_log",
                to="leavers.tasklog",
            ),
        ),
    ]
