# Generated by Django 4.1.3 on 2022-12-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0079_leavingrequest_security_clearance_level"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leavingrequest",
            options={
                "permissions": [
                    ("select_leaver", "Can select the user that is leaving")
                ]
            },
        ),
    ]
