# Generated by Django 4.1.4 on 2023-01-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0079_leavingrequest_security_clearance_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
