# Generated by Django 4.1.4 on 2023-01-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leavers", "0086_update_flows"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverinformation",
            name="is_floor_liaison_officer",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="is_health_and_safety_officer",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
