# Generated by Django 4.1.6 on 2023-02-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leavers", "0091_leavingrequest_docker_user_access_removed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leavingrequest",
            name="staff_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("civil_servant", "Civil servant"),
                    ("contractor", "Contractor (for example, Hays)"),
                    ("bench_contractor", "Bench contractor (for example, Profusion)"),
                    ("fast_streamers", "Civil Service Fast Stream"),
                    ("loan", "Loan"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
