# Generated by Django 4.1.10 on 2023-10-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leavers", "0094_leavingrequest_passman_access_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="cancelled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
