# Generated by Django 4.1.10 on 2023-10-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leavers", "0094_leavingrequest_passman_access_removed"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverinformation",
            name="cirrus_additional_information",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
