# Generated by Django 4.1.13 on 2024-01-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beis_service_now", "0004_servicenowlocation"),
        ("leavers", "0096_leaverinformation_cirrus_additional_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverinformation",
            name="service_now_directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="beis_service_now.servicenowdirectorate",
            ),
        ),
        migrations.AddField(
            model_name="leaverinformation",
            name="service_now_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="beis_service_now.servicenowlocation",
            ),
        ),
    ]
