# Generated by Django 4.2.11 on 2024-05-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beis_service_now", "0005_servicenowritm"),
        ("leavers", "0097_leaverinformation_service_now_directorate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leavingrequest",
            name="service_now_ritms",
            field=models.ManyToManyField(
                related_name="leaving_requests", to="beis_service_now.servicenowritm"
            ),
        ),
    ]
