# Generated by Django 3.2.9 on 2021-12-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivityStreamStaffSSOUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email_address", models.EmailField(max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                ("last_accessed", models.DateTimeField()),
                ("joined", models.DateTimeField()),
                ("email_user_id", models.CharField(max_length=255)),
                ("contact_email_address", models.EmailField(max_length=255, null=True)),
                ("became_inactive_on", models.DateTimeField(null=True)),
            ],
        ),
    ]
