version: '3'
# Network section required to avoid staff SSO IP collision
networks:
  inside:
    external: false
    internal: true
  default:
    ipam:
      driver: default
      config:
      -  subnet: 192.168.3.0/24
services:
  db:
    image: postgres:11
    networks:
        - inside
    environment:
      - POSTGRES_DB=leavers
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

  opensearch:
    image: opensearchproject/opensearch:1.2.3
    networks:
      - default
      - inside
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true" 
      - "DISABLE_SECURITY_PLUGIN=true"

  redis:
    image: redis:buster
    networks:
      - inside
    ports:
      - "6379:6379"

  leavers:
    build:
      context: .
      dockerfile: "docker/Dockerfile.dev"
    networks:
        - default
        - inside
    env_file: .env
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - "8001:8000"
    depends_on:
      - db
      - redis
      - opensearch
    restart: always

  celery:
    build:
      context: .
      dockerfile: "docker/Dockerfile.dev"
    networks:
      - inside
    env_file: .env
    command: celery -A core.celery worker -l INFO
    volumes:
      - ./:/app/
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: "docker/Dockerfile.dev"
    networks:
      - inside
    env_file: .env
    command: celery -A core.celery beat -l INFO
    depends_on:
      - db
      - redis
