version: '3'
networks:
  default:
    ipam:
      driver: default
      config:
      -  subnet: 192.168.3.0/24
services:
 db:
   image: postgres:11
   environment:
     - POSTGRES_DB=leavers
     - POSTGRES_PASSWORD=postgres
   ports:
     - "5432:5432"
   healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
 leavers:
   build:
      context: .
      dockerfile: "docker/Dockerfile.dev"
   env_file: .env
   command: python manage.py runserver 0.0.0.0:8000
   volumes:
     - ./:/app/
   ports:
     - "0.0.0.0:8000:8000"
   depends_on:
     - db
   restart: always




