version: '3'
services:
  utils:
    networks:
      - inside
    build:
      context: .
      dockerfile: "docker/Dockerfile.utils"
    platform: "linux/amd64"
    env_file: .env
    volumes:
    - ./:/app/
    restart: always
