version: '3'
# Network section required to avoid staff SSO IP collision
networks:
  inside:
    external: false
    internal: true
  default:
    ipam:
      driver: default
      config:
      -  subnet: 192.168.3.0/24
services:
  db:
    networks:
        - inside
    image: postgres:11
    environment:
      - POSTGRES_DB=leavers
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5

  leavers:
    networks:
        - default
        - inside
    build:
        context: .
        dockerfile: "docker/Dockerfile.dev"
    env_file: .env
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - "0.0.0.0:8001:8000"
    depends_on:
      - db
      - opensearch
    restart: always
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local

  opensearch:
    networks:
      - default
      - inside
    image: opensearchproject/opensearch:1.2.3
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true" 
      - "DISABLE_SECURITY_PLUGIN=true"

# redis:
#   networks:
#     - inside
#   image: redis:buster
#   ports:
#     - "6379:6379"
# celery:
#   build:
#      context: .
#      dockerfile: "docker/Dockerfile.dev"
#   command: celery -A config worker -l info
#   volumes:
#     - ./:/app/
#   depends_on:
#     - db
#     - redis
#   environment:
#     - DJANGO_SETTINGS_MODULE=config.settings.local
