version: "3"
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=leavers
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - ./setup/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./myignore/:/myignore/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  opensearch:
    image: opensearchproject/opensearch:2.3.0
    ports:
      - "9200:9200"
      - "9600:9600"
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"

  redis:
    image: redis:buster
    ports:
      - "6379:6379"

  leavers:
    build:
      context: .
      dockerfile: "docker/Dockerfile.dev"
    env_file: .env
    command: "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - db
      - redis
      - opensearch
    restart: unless-stopped
    stdin_open: true
    tty: true

  celery:
    build:
      context: .
      dockerfile: "docker/Dockerfile.dev"
    env_file: .env
    command: celery -A config.celery worker -l INFO
    volumes:
      - ./:/app/
    depends_on:
      - db
      - redis
    healthcheck:
      test: ["CMD-SHELL", "python -m dbt_copilot_python.celery_health_check.healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 2
      start_period: 5s

  celery-beat:
    build:
      context: .
      dockerfile: "docker/Dockerfile.dev"
    env_file: .env
    volumes:
      - ./:/app/
    command: celery -A config.celery beat -l INFO
    depends_on:
      - db
      - redis
