site_name: Leaving DIT Service
site_url: https://github.com/uktrade/jml
repo_url: https://github.com/uktrade/jml
plugins:
  - social
  - search:
      lang: en
theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: red
      accent: deep purple
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: red
      accent: deep purple

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/uktrade/jml/

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # /PS-IGNORE
  - js/tablesort.js

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
