[tool.poetry]
name = "jml"
version = "0.1.0"
description = "Joiners, Movers and Leavers Service"
authors = []
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
Celery = "==5.2.7"
crispy-forms-gds = "^0.2.3"
dataclasses-json = "==0.5.7"
dit-activity-stream = "==0.0.1"
django = "==3.2.15"
djangorestframework = "^3.12.4"
django-celery-beat = "^2.2.1"
django-celery-results = "==2.4.0"
django-compressor = "^2.4.1"
django-crispy-forms = "^1.14.0"
django-environ = "^0.8.1"
django-health-check = "==3.16.5"
django-log-formatter-ecs = "^0.0.5"
django-sass-processor = "^1.0.1"
django-staff-sso-client = "^3.1.1"
django-workflow-engine = "==0.0.21"
django-elasticsearch-dsl = "^7.2.1"
django-audit-log-middleware = "^0.0.4"
libsass = "==0.20.0"
mohawk = "^1.1.0"
psycopg2 = "^2.8.5"
pyjwt = "==2.4.0"
redis = "^4.0.2"
oauthlib = "==3.2.1"
requests-oauthlib = "==1.3.1"
sentry-sdk = "^1.1.0"
slack_sdk = "^3.12.0"
slackclient = "^2.9.3"
waitress = "==2.1.2"
whitenoise = "==5.2.0"
# OpenSearch
opensearch-py = "==1.0.0"
opensearch-dsl = "==1.0.0"
# GovUK Notify
notifications-python-client = "^6.3.0"
help-desk-client = "==0.2.0"
# Required for production
psycogreen = "==1.0.2"

[tool.poetry.group.dev.dependencies]
black = "^22.10.0"
django-stubs = "^1.12.0"
factory-boy = "^3.2.1"
faker = "^15.1.0"
flake8 = "^5.0.4"
freezegun = "^1.2.2"
isort = "^5.10.1"
mypy = "^0.982"
pytest = "^7.1.3"
pytest-cov = "^4.0.0"
pytest-django = "^4.5.2"
pytest-xdist = "^2.5.0"
responses = "^0.22.0"
types-certifi = "^2021.10.8.3"
types-freezegun = "^1.1.10"
types-requests = "^2.28.11.2"
types-oauthlib = "^3.2.0"
django-extensions = "^3.2.1"
pygraphviz = "^1.10"
pyparsing = "^3.0.9"
pydot = "^1.4.2"
poetry = "^1.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
