# Generated by Django 3.2.12 on 2022-04-06 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("users", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
            },
        ),
        migrations.CreateModel(
            name="PhysicalAsset",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="asset_registry.asset",
                    ),
                ),
                ("asset_number", models.CharField(max_length=50, unique=True)),
                ("finance_asset_number", models.CharField(max_length=50, unique=True)),
                ("category", models.CharField(choices=[], max_length=50)),
                ("status", models.CharField(choices=[], max_length=50)),
                ("manufacturer", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("serial_number", models.CharField(max_length=255)),
                ("purchase_date", models.DateField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("warranty_expire_date", models.DateField()),
                ("location", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=50)),
                ("date_assigned", models.DateField()),
                ("date_returned", models.DateField()),
                ("last_verified_date", models.DateField()),
            ],
            options={
                "verbose_name": "Physical Asset",
                "verbose_name_plural": "Physical Assets",
            },
            bases=("asset_registry.asset",),
        ),
        migrations.CreateModel(
            name="SoftwareAsset",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="asset_registry.asset",
                    ),
                ),
                ("software_name", models.CharField(max_length=50)),
                ("licence_number", models.CharField(max_length=50)),
                ("licence_password", models.CharField(max_length=50)),
                ("licences_available", models.IntegerField()),
                ("licences_issued", models.IntegerField()),
                ("renewal_date", models.DateField()),
            ],
            options={
                "verbose_name": "Software Asset",
                "verbose_name_plural": "Software Assets",
            },
            bases=("asset_registry.asset",),
        ),
    ]
