# Generated by Django 3.2.12 on 2022-04-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0002_activitystreamstaffssouser_available"),
        ("asset_registry", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="users",
            field=models.ManyToManyField(
                to="activity_stream.ActivityStreamStaffSSOUser"
            ),
        ),
    ]
