# Generated by Django 3.2.12 on 2022-04-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset_registry", "0002_alter_asset_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="physicalasset",
            name="category",
            field=models.CharField(
                choices=[
                    ("av_equipment", "AV Equipment"),
                    ("camera", "Camera"),
                    ("desktop", "Desktop"),
                    ("laptop", "Laptop"),
                    ("mifi_device", "Mi-Fi Device"),
                    ("mobile_screen", "Mobile Screen"),
                    ("monitor", "Monitor"),
                    ("port_replicator", "Port Replicator"),
                    ("printer", "Printer"),
                    ("sound_bar", "Sound Bar"),
                    ("speaker", "Speaker"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="physicalasset",
            name="date_returned",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="physicalasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("deployed", "Deployed"),
                    ("disposed_of", "Disposed Of"),
                    ("faulty", "Faulty"),
                    ("honme_use", "Home Use"),
                    ("loan_pool", "Loan Pool"),
                    ("lost_stolen", "Lost/Stolen"),
                    ("stock", "Stock"),
                    ("written_off", "Written Off Life Expectancy"),
                ],
                max_length=50,
            ),
        ),
    ]
