version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Check for fixme comments
          command: make check-fixme
      - run:
          name: Copy env file
          command: cp .env.ci .env
      - run:
          name: build containers
          command: make build
      - run:
          name: check for missing migrations
          command: make checkmigrations
      - run:
          name: run black (code formatting check)
          command: make black
      - run:
          name: run flake8 (coding standards compliance test)
          command: make flake8
      - run:
          name: run tests
          command: make pytest
      - run:
          name: Publish unit test coverage
          command: |
            wget -O codecov.sh https://codecov.io/bash
            bash ./codecov.sh -t ${CODECOV_TOKEN} -s test-reports -f "*.xml"
