FROM debian:bullseye
RUN apt-get update
RUN apt-get install -y wget gnupg2

ADD . /app
WORKDIR /app

# Install Cloudfoundry CLI
RUN wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
RUN echo "deb https://packages.cloudfoundry.org/debian stable main" | tee /etc/apt/sources.list.d/cloudfoundry-cli.list
RUN apt-get update
RUN apt-get install cf8-cli -y

# Add any other tools that can't be run on ARM
