FROM python:3.9.12
WORKDIR /app

RUN apt update
RUN apt install graphviz graphviz-dev -y

RUN pip install --upgrade pip

ADD requirements/dev.txt /app/requirements/dev.txt
RUN pip install -r requirements/dev.txt
ADD . /app
