FROM gcr.io/sre-docker-registry/py-node:3.10-18

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV POETRY_VIRTUALENVS_CREATE=false

WORKDIR /app

RUN apt-get update -y
RUN apt-get install -y graphviz graphviz-dev

RUN pip install --upgrade pip
RUN pip install poetry

COPY poetry.lock pyproject.toml /app/

RUN poetry install --with dev,testing --without production

COPY . /app/
