FROM python:3.13

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV POETRY_VIRTUALENVS_CREATE=false

WORKDIR /app

RUN apt-get update -y
RUN apt-get install -y graphviz graphviz-dev

RUN pip install --upgrade pip
RUN pip install poetry==2.1.1

COPY poetry.lock pyproject.toml /app/

RUN poetry install --with dev,testing --without production

COPY . /app/
