# Generated by Django 3.2.9 on 2021-12-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystreamstaffssouser",
            name="available",
            field=models.BooleanField(default=False),
        ),
    ]
