# Generated by Django 3.2.12 on 2022-04-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0002_activitystreamstaffssouser_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitystreamstaffssouser",
            name="email_address",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
