# Generated by Django 3.2.13 on 2022-07-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0003_alter_activitystreamstaffssouser_email_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitystreamstaffssouser",
            name="last_accessed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
