# Generated by Django 3.2.13 on 2022-07-05 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0004_alter_activitystreamstaffssouser_last_accessed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitystreamstaffssouser",
            name="email_address",
        ),
        migrations.CreateModel(
            name="ActivityStreamStaffSSOUserEmail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=255, unique=True)),
                (
                    "staff_sso_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="activity_stream.activitystreamstaffssouser",
                    ),
                ),
            ],
        ),
    ]
