# Generated by Django 3.2.13 on 2022-07-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0005_auto_20220705_1032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitystreamstaffssouseremail",
            name="staff_sso_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sso_emails",
                to="activity_stream.activitystreamstaffssouser",
            ),
        ),
    ]
