# Generated by Django 3.2.13 on 2022-07-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "activity_stream",
            "0006_alter_activitystreamstaffssouseremail_staff_sso_user",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystreamstaffssouser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
