# Generated by Django 3.2.13 on 2022-07-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0007_activitystreamstaffssouser_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitystreamstaffssouser",
            name="is_active",
        ),
    ]
