# Generated by Django 3.2.13 on 2022-07-08 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0008_remove_activitystreamstaffssouser_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceEmailAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_now_email_address",
                    models.EmailField(max_length=255, unique=True),
                ),
                (
                    "staff_sso_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_emails",
                        to="activity_stream.activitystreamstaffssouser",
                    ),
                ),
            ],
        ),
    ]
