# Generated by Django 3.2.14 on 2022-07-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0009_serviceemailaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystreamstaffssouser",
            name="uksbs_person_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
