# Generated by Django 3.2.14 on 2022-08-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0010_activitystreamstaffssouser_uksbs_person_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystreamstaffssouseremail",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
