# Generated by Django 3.2.15 on 2022-09-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0011_activitystreamstaffssouseremail_is_primary"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystreamstaffssouser",
            name="uksbs_person_id_override",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
