# Generated by Django 3.2.15 on 2022-10-21 09:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0012_activitystreamstaffssouser_uksbs_person_id_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystreamstaffssouser",
            name="employee_numbers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=list, size=None
            ),
        ),
    ]
