# Generated by Django 3.2.16 on 2022-10-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0013_activitystreamstaffssouser_employee_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystreamstaffssouser",
            name="service_now_email_address",
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
