# Generated by Django 3.2.16 on 2022-10-24 12:32

from django.db import migrations


def migrate_service_now_email_address(apps, schema_editor):
    SSOUser = apps.get_model("activity_stream", "ActivityStreamStaffSSOUser")

    qs = SSOUser.objects.prefetch_related("service_emails").all()

    for sso_user in qs:
        service_email_address = sso_user.service_emails.first()

        if service_email_address:
            sso_user.service_now_email_address = (
                service_email_address.service_now_email_address
            )
            sso_user.save(update_fields=["service_now_email_address"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "activity_stream",
            "0014_activitystreamstaffssouser_service_now_email_address",
        ),
    ]

    operations = [migrations.RunPython(migrate_service_now_email_address)]
