# Generated by Django 3.2.16 on 2022-10-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activity_stream", "0015_migrate_service_now_email_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystreamstaffssouser",
            name="service_now_user_id",
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name="ServiceEmailAddress",
        ),
    ]
