# Generated by Django 4.1.9 on 2023-06-29 15:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "activity_stream",
            "0017_alter_activitystreamstaffssouseremail_email_address_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activitystreamstaffssouser",
            name="service_now_email_address",
        ),
        migrations.RemoveField(
            model_name="activitystreamstaffssouser",
            name="service_now_user_id",
        ),
    ]
