# Generated by Django 4.1.9 on 2023-06-29 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beis_service_now", "0001_initial"),
        (
            "activity_stream",
            "0018_remove_activitystreamstaffssouser_service_now_email_address_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystreamstaffssouser",
            name="service_now_user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_stream_user",
                to="beis_service_now.servicenowuser",
            ),
        ),
    ]
