# Generated by Django 4.1.10 on 2023-10-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beis_service_now", "0003_alter_servicenowuser_email"),
        ("activity_stream", "0019_activitystreamstaffssouser_service_now_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystreamstaffssouser",
            name="service_now_users",
            field=models.ManyToManyField(
                related_name="activity_stream_users",
                to="beis_service_now.servicenowuser",
            ),
        ),
        migrations.RemoveField(
            model_name="activitystreamstaffssouser",
            name="service_now_user",
        ),
    ]
