from django.urls import reverse_lazy

from config.settings.base import *  # type: ignore # noqa

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


if not DEV_TOOLS_ENABLED:
    DEV_TOOLS_ENABLED = True

    INSTALLED_APPS += [  # type: ignore
        "dev_tools.apps.DevToolsConfig",
    ]

    LOGIN_URL = reverse_lazy("dev_tools:index")

    MIDDLEWARE.append("dev_tools.middleware.DevToolsLoginRequiredMiddleware")  # type: ignore

if "core.middleware.IndexCurrentUser" in MIDDLEWARE:
    MIDDLEWARE.remove("core.middleware.IndexCurrentUser")


# EMAIL TEMPLATES
TEMPLATE_ID_LEAVER_THANK_YOU_EMAIL = "xxx"
TEMPLATE_ID_LEAVER_NOT_IN_UKSBS_HR_REMINDER = "xxx"
TEMPLATE_ID_LEAVER_NOT_IN_UKSBS_LM_REMINDER = "xxx"
TEMPLATE_ID_LINE_MANAGER_CORRECTION_EMAIL = "xxx"
TEMPLATE_ID_LINE_MANAGER_CORRECTION_HR_EMAIL = "xxx"
TEMPLATE_ID_LINE_MANAGER_CORRECTION_REPORTED_LM_EMAIL = "xxx"
TEMPLATE_ID_LINE_MANAGER_NOTIFICATION_EMAIL = "xxx"
TEMPLATE_ID_LINE_MANAGER_REMINDER_EMAIL = "xxx"
TEMPLATE_ID_LINE_MANAGER_THANKYOU_EMAIL = "xxx"
TEMPLATE_ID_IT_OPS_ASSET_EMAIL = "xxx"
TEMPLATE_ID_CSU4_EMAIL = "xxx"
TEMPLATE_ID_OCS_LEAVER_EMAIL = "xxx"
TEMPLATE_ID_OCS_OAB_LOCKER_EMAIL = "xxx"
TEMPLATE_ID_SECURITY_TEAM_OFFBOARD_BP_LEAVER_EMAIL = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_BP_REMINDER_DAY_AFTER_LWD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_BP_REMINDER_TWO_DAYS_AFTER_LWD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_BP_REMINDER_ON_LD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_BP_REMINDER_ONE_DAY_AFTER_LD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_BP_REMINDER_TWO_DAYS_AFTER_LD_LM = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_BP_REMINDER_TWO_DAYS_AFTER_LD_PROC = "xxx"
TEMPLATE_ID_SECURITY_TEAM_OFFBOARD_RK_LEAVER_EMAIL = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_RK_REMINDER_DAY_AFTER_LWD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_RK_REMINDER_TWO_DAYS_AFTER_LWD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_RK_REMINDER_ON_LD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_RK_REMINDER_ONE_DAY_AFTER_LD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_RK_REMINDER_TWO_DAYS_AFTER_LD_LM = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_RK_REMINDER_TWO_DAYS_AFTER_LD_PROC = "xxx"
TEMPLATE_ID_SRE_NOTIFICATION = "xxx"
TEMPLATE_ID_SRE_REMINDER_DAY_AFTER_LWD = "xxx"
TEMPLATE_ID_SRE_REMINDER_ONE_DAY_AFTER_LD = "xxx"
TEMPLATE_ID_SRE_REMINDER_TWO_DAYS_AFTER_LD_PROC = "xxx"
