from django.urls import reverse_lazy

from config.settings.base import *  # type: ignore # noqa

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"


if not DEV_TOOLS_ENABLED:
    DEV_TOOLS_ENABLED = True

    INSTALLED_APPS += [  # type: ignore
        "dev_tools.apps.DevToolsConfig",
    ]

    LOGIN_URL = reverse_lazy("dev_tools:index")

    MIDDLEWARE.append("dev_tools.middleware.DevToolsLoginRequiredMiddleware")  # type: ignore

if "core.middleware.IndexCurrentUser" in MIDDLEWARE:
    MIDDLEWARE.remove("core.middleware.IndexCurrentUser")


CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "cache-for-testing",
        "KEY_PREFIX": "cache",
    }
}


# EMAIL TEMPLATES
TEMPLATE_ID_LEAVER_THANK_YOU_EMAIL = "xxx"
TEMPLATE_ID_LEAVER_NOT_IN_UKSBS_HR_REMINDER = "xxx"
TEMPLATE_ID_LEAVER_NOT_IN_UKSBS_LM_REMINDER = "xxx"
TEMPLATE_ID_LINE_MANAGER_CORRECTION_EMAIL = "xxx"
TEMPLATE_ID_LINE_MANAGER_CORRECTION_HR_EMAIL = "xxx"
TEMPLATE_ID_LEAVER_IN_PAY_CUT_OFF_HR_EMAIL = "xxx"
TEMPLATE_ID_LINE_MANAGER_CORRECTION_REPORTED_LM_EMAIL = "xxx"
TEMPLATE_ID_LINE_MANAGER_NOTIFICATION_EMAIL = "xxx"
TEMPLATE_ID_LINE_MANAGER_REMINDER_EMAIL = "xxx"
TEMPLATE_ID_LINE_MANAGER_THANKYOU_EMAIL = "xxx"
TEMPLATE_ID_LINE_MANAGER_OFFLINE_SERVICE_NOW_EMAIL = "xxx"
TEMPLATE_ID_FEETHAM_SECURITY_PASS_OFFICE_EMAIL = "xxx"
TEMPLATE_ID_IT_OPS_ASSET_EMAIL = "xxx"
TEMPLATE_ID_CLU4_EMAIL = "xxx"
TEMPLATE_ID_OCS_LEAVER_EMAIL = "xxx"
TEMPLATE_ID_OCS_OAB_LOCKER_EMAIL = "xxx"
TEMPLATE_ID_HEALTH_AND_SAFETY_EMAIL = "xxx"
TEMPLATE_ID_COMAEA_EMAIL = "xxx"
TEMPLATE_ID_BUSINESS_CONTINUITY_LEAVER_EMAIL = "xxx"
TEMPLATE_ID_SECURITY_TEAM_OFFBOARD_BP_LEAVER_EMAIL = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_BP_REMINDER_DAY_AFTER_LWD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_BP_REMINDER_TWO_DAYS_AFTER_LWD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_BP_REMINDER_ON_LD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_BP_REMINDER_ONE_DAY_AFTER_LD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_BP_REMINDER_TWO_DAYS_AFTER_LD_LM = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_BP_REMINDER_TWO_DAYS_AFTER_LD_PROC = "xxx"
TEMPLATE_ID_SECURITY_TEAM_OFFBOARD_RK_LEAVER_EMAIL = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_RK_REMINDER_DAY_AFTER_LWD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_RK_REMINDER_TWO_DAYS_AFTER_LWD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_RK_REMINDER_ON_LD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_RK_REMINDER_ONE_DAY_AFTER_LD = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_RK_REMINDER_TWO_DAYS_AFTER_LD_LM = "xxx"
TEMPLATE_ID_SECURITY_OFFBOARD_RK_REMINDER_TWO_DAYS_AFTER_LD_PROC = "xxx"
TEMPLATE_ID_SRE_NOTIFICATION = "xxx"
TEMPLATE_ID_SRE_REMINDER_DAY_AFTER_LWD = "xxx"
TEMPLATE_ID_SRE_REMINDER_ONE_DAY_AFTER_LD = "xxx"
TEMPLATE_ID_SRE_REMINDER_TWO_DAYS_AFTER_LD_PROC = "xxx"

CLU4_EMAIL = "test@example.com"  # /PS-IGNORE
FEETHAM_SECURITY_PASS_OFFICE_EMAIL = "test@example.com"  # /PS-IGNORE
IT_OPS_EMAIL = "test@example.com"  # /PS-IGNORE
OCS_EMAIL = "test@example.com"  # /PS-IGNORE
OCS_OAB_LOCKER_EMAIL = "test@example.com"  # /PS-IGNORE
SECURITY_TEAM_VETTING_EMAIL = "test@example.com"  # /PS-IGNORE
SECURITY_TEAM_BUILDING_PASS_EMAIL = "test@example.com"  # /PS-IGNORE
SECURITY_TEAM_ROSA_EMAIL = "test@example.com"  # /PS-IGNORE
SRE_EMAIL = "test@example.com"  # /PS-IGNORE
HR_UKSBS_CORRECTION_EMAIL = "test@example.com"  # /PS-IGNORE
COMAEA_EMAIL = "test@example.com"  # /PS-IGNORE
HEALTH_AND_SAFETY_EMAIL = "test@example.com"  # /PS-IGNORE
BUSINESS_CONTINUITY_EMAIL = "test@example.com"  # /PS-IGNORE

HELP_DESK_INTERFACE = "help_desk_client.interfaces.HelpDeskStubbed"
STAFF_SSO_INTERFACE = "core.staff_sso.interfaces.StaffSSOStubbed"
SERVICE_NOW_INTERFACE = "core.service_now.interfaces.ServiceNowStubbed"
UKSBS_INTERFACE = "core.uksbs.interfaces.UKSBSStubbed"
PEOPLE_FINDER_INTERFACE = "core.people_finder.interfaces.PeopleFinderStubbed"
PEOPLE_DATA_INTERFACE = "core.people_data.interfaces.PeopleDataStubbed"
