# Generated by Django 3.2.12 on 2022-03-31 16:42

import uuid

from django.db import migrations, models


def add_user_ids(apps, schema_editor):
    User = apps.get_model("user", "User")
    for user in User.objects.all():
        user.user_id = str(uuid.uuid4())
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(add_user_ids),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
