# Generated by Django 4.1.9 on 2023-06-29 15:15

from typing import Any, List

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[Any] = []

    operations = [
        migrations.CreateModel(
            name="ServiceNowObject",
            fields=[
                (
                    "sys_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceNowAsset",
            fields=[
                (
                    "servicenowobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="beis_service_now.servicenowobject",
                    ),
                ),
            ],
            bases=("beis_service_now.servicenowobject",),
        ),
        migrations.CreateModel(
            name="ServiceNowDirectorate",
            fields=[
                (
                    "servicenowobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="beis_service_now.servicenowobject",
                    ),
                ),
            ],
            bases=("beis_service_now.servicenowobject",),
        ),
        migrations.CreateModel(
            name="ServiceNowUser",
            fields=[
                (
                    "servicenowobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="beis_service_now.servicenowobject",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
            bases=("beis_service_now.servicenowobject",),
        ),
    ]
