# Generated by Django 4.1.10 on 2023-09-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beis_service_now", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicenowasset",
            name="asset_tag",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowasset",
            name="assigned_to_display_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowasset",
            name="assigned_to_sys_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowasset",
            name="display_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowasset",
            name="install_status",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowasset",
            name="model",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowasset",
            name="model_category",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowasset",
            name="serial_number",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowasset",
            name="substatus",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowdirectorate",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowuser",
            name="manager_sys_id",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowuser",
            name="manager_user_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowuser",
            name="name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicenowuser",
            name="user_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
