# Generated by Django 4.1.10 on 2023-10-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("beis_service_now", "0002_servicenowasset_asset_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicenowuser",
            name="email",
            field=models.CharField(max_length=255),
        ),
    ]
