# Generated by Django 4.1.13 on 2024-01-18 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("beis_service_now", "0003_alter_servicenowuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceNowLocation",
            fields=[
                (
                    "servicenowobject_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="beis_service_now.servicenowobject",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            bases=("beis_service_now.servicenowobject",),
        ),
    ]
