# Generated by Django 4.2.11 on 2024-05-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beis_service_now", "0004_servicenowlocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceNowRITM",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.BooleanField()),
                ("user_sys_id", models.CharField(max_length=255)),
                ("request_id", models.CharField(max_length=255)),
            ],
        ),
    ]
