# Generated by Django 3.2.14 on 2022-07-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betaservicefeedback",
            name="satisfaction",
            field=models.CharField(
                choices=[
                    ("very_satisfied", "Very satisfied"),
                    ("satisfied", "Satisfied"),
                    ("neutral", "Neither satisfied or dissatisfied"),
                    ("dissatisfied", "Dissatisfied"),
                    ("very_dissatisfied", "Very dissatisfied"),
                ],
                max_length=30,
            ),
        ),
    ]
