# Generated by Django 3.2.15 on 2022-09-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_betaservicefeedback_satisfaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="betaservicefeedback",
            options={
                "verbose_name": "Beta Feedback Submission",
                "verbose_name_plural": "Beta Feedback Submissions",
            },
        ),
    ]
