# Generated by Django 4.1.6 on 2023-02-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0003_alter_betaservicefeedback_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betaservicefeedback",
            name="satisfaction",
            field=models.CharField(
                choices=[
                    ("very_dissatisfied", "Very dissatisfied"),
                    ("dissatisfied", "Dissatisfied"),
                    ("neutral", "Neither satisfied or dissatisfied"),
                    ("satisfied", "Satisfied"),
                    ("very_satisfied", "Very satisfied"),
                ],
                max_length=30,
            ),
        ),
    ]
