# Generated by Django 4.1.7 on 2023-02-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0004_alter_betaservicefeedback_satisfaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="betaservicefeedback",
            name="submitted_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
