name: CI
on:
  push:
    branches: "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Poetry
        run: |
          pip install -U pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --with docs

      - name: Check for fixme comments
        run: make check-fixme

      - name: Copy env file
        run: make cp .env.ci .env

      - name: Build containers
        run: make build

      - name: launch containers
        run: make up-detached

      - name: check for missing migrations
        run: make checkmigrations

      - name: Run black (code formatting check)
        run: make black

      - name: Run flake8 (coding standards compliance test)
        run: make flake8

      - name: Run mypy (type checking)
        run: make mypy

      - name: Run tests
        run: make pytest

      - run: make down
