name: Build and publish docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check-ex:
    runs-on: ubuntu-latest
    steps:
      - uses: uktrade/ex-project-action@v1
